constructor
N1kla3/Prosem pull request #14
Opened 2020-09-23 10:39 UTC by vadimmmmm

2020-09-23 11:05 UTC, N1kla3 requested changes

2020-09-23 11:05 UTC, N1kla3 commented on ConstrFormalization/constructor.scs
> +//        super(s, list);
этого нету в scs

2020-09-23 11:05 UTC, N1kla3 commented on ConstrFormalization/constructor.scs
> + => nrel_code_block:..;;
нету concept_codeblock

2020-09-23 11:55 UTC, ShteinR commented
В третьей строчке там 3 точки должно быть вроде и у нас тип множество аргументов, так что надо показать что там множество, а не пустой кружочек

2020-09-23 13:39 UTC, N1kla3 commented
> В третьей строчке там 3 точки должно быть вроде и у нас тип множество аргументов, так что надо показать что там множество, а не пустой кружочек

так то у нас его нету как я знаю

2020-09-23 13:41 UTC, ShteinR commented
> > В третьей строчке там 3 точки должно быть вроде и у нас тип множество аргументов, так что надо показать что там множество, а не пустой кружочек
> 
> так то у нас его нету как я знаю

Че?

2020-09-24 19:51 UTC, N1kla3 commented
> > > В третьей строчке там 3 точки должно быть вроде и у нас тип множество аргументов, так что надо показать что там множество, а не пустой кружочек
> > 
> > 
> > так то у нас его нету как я знаю
> 
> Че?

ну типо должно быть что-то вроде concept_parametrs, но как я знаю у нас нету в базе такого. Надо сделать!

2020-09-28 21:14 UTC, N1kla3 commented on ConstrFormalization/constructor.scs
> +sc_node_not_relation -> concept_arguments;;
это вообще не надо

2020-09-28 21:16 UTC, N1kla3 commented on ConstrFormalization/constructor.scs
> +	->constructor_args(*<-concept_arguments;;
ExampleClass_conctructor_1
ExampleClass_conctructor_1_args

2020-09-28 21:17 UTC, ShteinR commented on ConstrFormalization/constructor.scs
> + => nrel_code_block:..;;
и nrel_conctructor_body

2020-09-28 21:17 UTC, N1kla3 requested changes
almost

2020-09-28 21:27 UTC, N1kla3 approved these changes
Все норм пока мы не начали все изменять

2020-09-28 21:28 UTC, ShteinR approved these changes

2020-09-28 21:29 UTC, merged