Nikitaaaaa
N1kla3/Prosem pull request #24
Opened 2020-09-26 20:50 UTC by Fenydude

2020-09-26 20:51 UTC, Fenydude commented
Это пиздец

2020-09-27 07:48 UTC, N1kla3 requested changes
Еще у тебя нету примера кода для которого ты делал пример if else.

2020-09-27 07:48 UTC, N1kla3 commented on ConstrFormalization/if-else.scs
> +sc_node_not_relation-> concept_if(*
Нам не на до указывать `sc_node_not_relation` здесь, это есть в базе.
И тебе надо ссылатся на элемент множества `concept_if` ,а не на само множество.
То есть 
`concept_code_block->some_code(*->..if_1(*<-concept_if*);;*);;`

2020-09-27 07:49 UTC, N1kla3 commented on ConstrFormalization/if-else.scs
> +sc_node_not_relation-> concept_else(*
нету связи if c else

2020-09-27 08:30 UTC, ShteinR commented on ConstrFormalization/if-else.scs
> +->..code_block(*<-concept_code_block;;*);;
Может быть тут надо указать что это не просто блок кода, а непосредственно тело ифа

2020-09-29 17:16 UTC, ShteinR requested changes

2020-09-29 17:16 UTC, ShteinR commented on ConstrFormalization/if-else.scs
> +    ->rrel_condition_else:..else_1(*
Rrel_condition_false скорее, чтобы мы потом могли перейти в else if(), оттуда опять тру фолс и тд, пока не дойдём до else
Пока мы не решили все переписать, в остальном норм вроде наверное я думаю

2020-10-12 13:13 UTC, closed without merging