field call
N1kla3/Prosem pull request #26
Opened 2020-09-27 20:53 UTC by N1kla3

2020-09-27 21:01 UTC, ShteinR commented on ConstrFormalization/object_call.scs
> +		<-SomeClass;;
тут не уверен, он же не часть класса, он его экземпляр

2020-09-27 21:01 UTC, ShteinR commented on ConstrFormalization/object_call.scs
> +	->SomeClass_object(*
тогда уж не object, a reference или тип того

2020-09-27 21:20 UTC, ShteinR requested changes

2020-09-27 21:20 UTC, ShteinR commented on ConstrFormalization/object_call.scs
> +		<=nrel_object_of:SomeClass;;
так вообще не уверен что можно делать, обычно же ...=>nrel:...

2020-09-27 21:20 UTC, ShteinR commented on ConstrFormalization/object_call.scs
> +		<-concept_reference;;
concept_reference_type

2020-09-27 21:20 UTC, ShteinR commented on ConstrFormalization/object_call.scs
> +		=> call_field:SomeClass_object_field(*
nrel_field_call

2020-09-27 21:24 UTC, N1kla3 commented on ConstrFormalization/object_call.scs
> +		<=nrel_object_of:SomeClass;;
можно оло

2020-10-03 08:21 UTC, ShteinR approved these changes
Я надеюсь норм

2020-10-03 08:21 UTC, merged