corrected
N1kla3/Prosem pull request #32
Opened 2020-10-05 20:44 UTC by N1kla3

2020-10-06 15:29 UTC, ShteinR requested changes

2020-10-06 15:29 UTC, ShteinR commented on ConstrFormalization/for.scs
> +            =>nrel_function_prototype:operator_less;;
Сделай более общее понятие, тип множество операторов сравнения

2020-10-06 15:29 UTC, ShteinR commented on ConstrFormalization/for.scs
> +        =>nrel_function_prototype:operator_decrement;;
И тут, но не сравнения

2020-10-06 15:29 UTC, ShteinR commented on ConstrFormalization/while.scs
> +                                    =>nrel_function_prototype:operator_less;;
И тут

2020-10-07 19:37 UTC, N1kla3 commented on ConstrFormalization/for.scs
> +            =>nrel_function_prototype:operator_less;;
Так ты можешь там вообще функцию рандомную вызывать. Так что нет

2020-10-07 19:38 UTC, N1kla3 commented on ConstrFormalization/for.scs
> +        =>nrel_function_prototype:operator_decrement;;
same

2020-10-07 19:38 UTC, N1kla3 commented on ConstrFormalization/while.scs
> +                                    =>nrel_function_prototype:operator_less;;
same

2020-10-08 16:34 UTC, ShteinR requested changes
Come on!!!!!!!!!

2020-10-08 16:34 UTC, ShteinR commented on ConstrFormalization/for.scs
> +            =>nrel_function_prototype:operator_less;;
Ну так, значит там надо что-то еще более общее поставить, ибо просто какой-то левый оператор меньше это вообще херь полная, камон, николай

2020-10-08 16:34 UTC, ShteinR commented on ConstrFormalization/for.scs
> +        =>nrel_function_prototype:operator_decrement;;
Same

2020-10-08 16:34 UTC, ShteinR commented on ConstrFormalization/while.scs
> +                                    =>nrel_function_prototype:operator_less;;
....

2020-10-08 18:16 UTC, N1kla3 commented on ConstrFormalization/for.scs
> +            =>nrel_function_prototype:operator_less;;
Ты клоун? В сорс коде меньше значит и тут меньше

2020-10-08 18:16 UTC, N1kla3 commented on ConstrFormalization/for.scs
> +        =>nrel_function_prototype:operator_decrement;;
Same

2020-10-08 18:18 UTC, N1kla3 commented
Все должно быть как в коде, в коде меньше значит тут тоже меньше, в коде декремент и тут значит декремент

2020-10-09 21:48 UTC, ShteinR approved these changes
Tjapos

2020-10-09 21:48 UTC, merged