class_field
N1kla3/Prosem pull request #45
Opened 2020-10-18 15:51 UTC by vadimmmmm

2020-10-18 15:55 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +concept_class ->....ExapmleClass(*
Тут 2 точки

2020-10-18 15:55 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +	=>inclusion:class_field(*
А  тут нрел не помешает)
И оно должно входить в какое-то множество, наверное, раз от него отношение идет

2020-10-18 15:55 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		=>nrel_arguments:..(*
А тут 3 точки
А что такое аргументы поля класса?

2020-10-18 15:55 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +			->rrel_1:..;;
И тут

2020-10-18 16:16 UTC, N1kla3 commented on ConstrFormalization/class_field.scs
> +			->rrel_1:..;;
я вообще ничего не понял

2020-10-18 16:18 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +			->rrel_1:..;;
3 точки там, вместо двух

2020-10-18 16:18 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +			->rrel_1:..;;
........

2020-10-18 16:18 UTC, N1kla3 commented on ConstrFormalization/class_field.scs
> +	=>inclusion:class_field(*
у нас как бы есть специальное отношение `nrel_class_field`

2020-10-18 16:19 UTC, N1kla3 requested changes
gg

2020-10-18 17:22 UTC, N1kla3 reviewed
обьясните, зачем здесь аргументы

2020-10-18 17:23 UTC, N1kla3 commented
а где пример кода на джаве

2020-10-18 17:24 UTC, N1kla3 commented
нету модификатора доступа итд

2020-10-18 18:24 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +	=>nrel_class_field:class_field(*
У нас это сделано как отношение между классом и переменной, так что мб добавить в скобках что это входит во множество переменных

2020-10-18 18:25 UTC, ShteinR commented
> обьясните, зачем здесь аргументы

Тоже хз

2020-10-22 17:38 UTC, vadimmmmm commented on ConstrFormalization/class_field.scs
> +	=>nrel_class_field:class_field(*
Где в скобка? тип class_field(*
=>inclusion:concept_variable;;
*)????

2020-10-22 19:33 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +	=>nrel_class_field:class_field(*
А inclusion  зачем?) Просто -> достаточно

2020-10-22 19:33 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		=>nrel_variable:..(*
И вот это тоже зачем?

2020-10-22 20:50 UTC, vadimmmmm commented on ConstrFormalization/class_field.scs
> +		=>nrel_variable:..(*
nrel_variable не нужно?

2020-10-22 21:16 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		=>nrel_variable:..(*
Нет, у нас же поле класса это отношение между классом и переменной, значит class_field это переменная

2020-11-03 17:43 UTC, N1kla3 requested changes
1)Нету примера кода на джаве
2)Нету абсолютно никакого описания переменной
3)название поля не соответствует стандарту

2020-11-04 11:04 UTC, N1kla3 requested changes
У МЕНЯ НЕТ СЛОВ!!!!!!!

2020-11-04 11:11 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		=>nrel_main_idtf:private;;
Камон

2020-11-04 11:11 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		<-data_type;;
Хз зачем тут тип данных, но можно просто concept_integer, наверное, а можно сделать дата_тайп отношением между переменной и чем-то, хз чем

2020-11-06 11:48 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		=>nrel_main_idtf:private;;
Камонх2))))

2020-11-08 19:35 UTC, ShteinR commented on ConstrFormalization/class_field.scs
> +		<-private(*
=> nrel_access_modifier:concept_access_modifier_private;;

2020-11-09 15:29 UTC, ShteinR approved these changes

2020-11-10 10:18 UTC, N1kla3 approved these changes

2020-11-11 19:23 UTC, merged